/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author JUan JOse Rua
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_historial = new javax.swing.JButton();
        btn_editfact = new javax.swing.JButton();
        btn_BuscFact = new javax.swing.JButton();
        btn_verfact = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_editusu = new javax.swing.JButton();
        btn_crearusu = new javax.swing.JButton();
        btn_crearpr = new javax.swing.JButton();
        btn_editpr = new javax.swing.JButton();
        btn_buscarpr = new javax.swing.JButton();
        btn_listProd = new javax.swing.JButton();
        btn_cerrarsesi = new javax.swing.JButton();
        btn_acerca = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        btn_historial.setText("HISTORIAL");
        btn_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historialActionPerformed(evt);
            }
        });

        btn_editfact.setText("EDITAR FACTURA");
        btn_editfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editfactActionPerformed(evt);
            }
        });

        btn_BuscFact.setText("BUSCAR FACTURA");
        btn_BuscFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscFactActionPerformed(evt);
            }
        });

        btn_verfact.setText("VER FACTURAS");
        btn_verfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verfactActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("QUESERA LA 81");

        jLabel2.setText("BIENVENIDO/A");

        btn_editusu.setText("EDITAR USUARIO");
        btn_editusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editusuActionPerformed(evt);
            }
        });

        btn_crearusu.setText("CREAR USUARIO");
        btn_crearusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearusuActionPerformed(evt);
            }
        });

        btn_crearpr.setText("CREAR PRODUCTO");
        btn_crearpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearprActionPerformed(evt);
            }
        });

        btn_editpr.setText("EDITAR PRODUCTO");
        btn_editpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editprActionPerformed(evt);
            }
        });

        btn_buscarpr.setText("BUSCAR PRODUCTO");
        btn_buscarpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarprActionPerformed(evt);
            }
        });

        btn_listProd.setText("LISTA DE PRODUCTOS");
        btn_listProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listProdActionPerformed(evt);
            }
        });

        btn_cerrarsesi.setText("CERRAR SESION");
        btn_cerrarsesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarsesiActionPerformed(evt);
            }
        });

        btn_acerca.setText("ACERCA DE");
        btn_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acercaActionPerformed(evt);
            }
        });

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_listProd)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_buscarpr)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btn_editusu)
                                                .addComponent(btn_crearusu)
                                                .addComponent(btn_cerrarsesi))
                                            .addGap(36, 36, 36)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btn_editpr)
                                                .addComponent(btn_crearpr))))
                                    .addGap(4, 4, 4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_acerca)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editusu)
                    .addComponent(btn_crearpr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_crearusu)
                    .addComponent(btn_editpr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cerrarsesi)
                    .addComponent(btn_buscarpr))
                .addGap(18, 18, 18)
                .addComponent(btn_listProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_acerca)
                    .addComponent(btn_salir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarsesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarsesiActionPerformed
        // TODO add your handling code here:
        Cerrar_sesion cs = new Cerrar_sesion();
        cs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cerrarsesiActionPerformed

    private void btn_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historialActionPerformed
        historial ad = new historial();
        ad.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_btn_historialActionPerformed

    private void btn_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acercaActionPerformed
        Acerca_De ac = new Acerca_De();
        ac.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_acercaActionPerformed

    private void btn_editfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editfactActionPerformed
        Edit_Fact f = new Edit_Fact();
        f.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_btn_editfactActionPerformed

    private void btn_BuscFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscFactActionPerformed
        // TODO add your handling code here:
        Buscar_Cont b = new Buscar_Cont();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_BuscFactActionPerformed

    private void btn_verfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verfactActionPerformed
        // TODO add your handling code here:
        Contabilidad c = new Contabilidad();
        c.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btn_verfactActionPerformed

    private void btn_listProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listProdActionPerformed
        // TODO add your handling code here:
        ListarP lp = new ListarP();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_listProdActionPerformed

    private void btn_buscarprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarprActionPerformed
        // TODO add your handling code here:
        Buscar_producto bp = new Buscar_producto();
        bp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_buscarprActionPerformed

    private void btn_editprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editprActionPerformed
        // TODO add your handling code here:
        Actualizar_producto ap = new Actualizar_producto();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_editprActionPerformed

    private void btn_crearprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearprActionPerformed
        // TODO add your handling code here:
        Productos p = new Productos();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_crearprActionPerformed

    private void btn_crearusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearusuActionPerformed
        // TODO add your handling code here:
        Crear_usuario crearus = new Crear_usuario();
        crearus.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_crearusuActionPerformed

    private void btn_editusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editusuActionPerformed
        // TODO add your handling code here:
        Editar_usuario editus = new Editar_usuario();
        editus.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_editusuActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscFact;
    private javax.swing.JButton btn_acerca;
    private javax.swing.JButton btn_buscarpr;
    private javax.swing.JButton btn_cerrarsesi;
    private javax.swing.JButton btn_crearpr;
    private javax.swing.JButton btn_crearusu;
    private javax.swing.JButton btn_editfact;
    private javax.swing.JButton btn_editpr;
    private javax.swing.JButton btn_editusu;
    private javax.swing.JButton btn_historial;
    private javax.swing.JButton btn_listProd;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_verfact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
